// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOt81bB48eyopuRmO3vTWPU-1XmTH6bs0',
    appId: '1:30970898395:web:bfd01343d118d2c15829fe',
    messagingSenderId: '30970898395',
    projectId: 'jobgo-4e864',
    authDomain: 'jobgo-4e864.firebaseapp.com',
    storageBucket: 'jobgo-4e864.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKqmz9hw6tqR6OX96dd_P8_wIGeBW55Hk',
    appId: '1:30970898395:android:97cd5083905aa55a5829fe',
    messagingSenderId: '30970898395',
    projectId: 'jobgo-4e864',
    storageBucket: 'jobgo-4e864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7R6BFNcOocNVd7uF35XNqWd4DHreJmFI',
    appId: '1:30970898395:ios:84051957480ff6c05829fe',
    messagingSenderId: '30970898395',
    projectId: 'jobgo-4e864',
    storageBucket: 'jobgo-4e864.firebasestorage.app',
    iosBundleId: 'com.example.jobgo',
  );
}
